#!/usr/bin/env python
"""
This script to restart django-service every 4 am
Don't forget to change the user
"""

from crontab import CronTab

def at4():
	myCron = CronTab(user='handry')

	job = myCron.new(command='systemctl restart djangorun.service', comment='restart-django-service')
	job.hour.on(4)

	myCron.write()

	for jb in myCron:
		print jb


def at5():
	myCron = CronTab(user='handry')

	job = myCron.new(command='fuser 8000/tcp >> running.txt', comment='restart-django-service')
	# job.hour.on(5)
	job.minute.every(1)

	myCron.write()	

	for jb in myCron:
		print jb


# main program
at4()
# at5()


