#!/bin/bash
# This script to running django application, 
# But change the variable to corresponding environment

ip="0.0.0.0:8080"
commandEx="/home/handry/Documents/belajarPython/webIKP/website/manage.py runserver"
pythonEnv="/home/handry/Documents/belajarPython/webIKP/env/bin/python"

$pythonEnv $commandEx $ip

