#!/usr/bin/env python
"""
This script to kill port 8000 which django server running.
If the django use different port (ex. 8080) change port in 'comman variable'
"""

import subprocess

def getPID():
	command = 'fuser 8000/tcp'
	process = subprocess.Popen(command.split(), stdout=subprocess.PIPE)
	output, error = process.communicate()
	result = output.split(' ')
	servicePID = result[-1]

	return servicePID


def killPID(pid):
	commandKill = 'kill ' + pid
	processKill = subprocess.Popen(commandKill.split(), stdout=subprocess.PIPE)
	output, error = processKill.communicate()
	msg = 'Django service killed successfully'

	return msg


if getPID() == '':
	msg = 'Django service not running'
	print msg
	quit()
else:
	print killPID(getPID())